version: '3'

services:
  nginx:            #服务名称用户自定义
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true #解决NGINX的文件调用权限
  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment:    # 指定 root 用户的密码
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:latest
  shi_blogs:
    image: shi_blogs:latest
    build: .    # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8181:8181
    depends_on:   # 依赖于mysql、redis，其实可以不填，默认已经表示可以
      - mysql
      - redis